<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class StarSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        $starPlayers = [
            [
                'name' => 'Akhorne the Squirrel',
                'ma' => '7',
                'st' => '1',
                'ag' => '2',
                'pa' => '0',
                'av' => '6',
                'cost' => 80000,
                'skills' => [5, 6, 9, 14, 19, 28],
                'traits' => [23, 26, 35, 39],
                'special' => 'Blind Rage',
                'description' => 'Akhorne may choose to re-roll the D6 when rolling for the Dauntless skill.',
                'display' => true,
                'regions' => [],
                'rules' => [],
            ],
            [
                'name' => 'Anqi Panqi',
                'ma' => '7',
                'st' => '4',
                'ag' => '5',
                'pa' => '6',
                'av' => '10',
                'cost' => 150000,
                'skills' => [13, 54, 62],
                'traits' => [23],
                'special' => 'Savage Blow',
                'description' => 'Once per game, when Anqi performs a Block action against an opposition player, he may choose to re-roll any number of the Block dice.',
                'display' => true,
                'regions' => [4],
                'rules' => [],
            ],
            [
                'name' => 'Barik Farblast',
                'ma' => '6',
                'st' => '3',
                'ag' => '4',
                'pa' => '3',
                'av' => '9',
                'cost' => 80000,
                'skills' => [24, 40, 44, 48, 64],
                'traits' => [23, 33],
                'special' => 'Blast It!',
                'description' => 'Once per game, when Barik makes a Hail Mary Pass, he may re-roll any scatter results for determining where the ball lands, and any friendly player attempting to catch the ball gains an additional +1 modifier to the roll.',
                'display' => true,
                'regions' => [3, 5, 8],
                'rules' => [],
            ],
            [
                'name' => 'Bilerot Vomitflesh',
                'ma' => '4',
                'st' => '5',
                'ag' => '4',
                'pa' => '6',
                'av' => '10',
                'cost' => 180000,
                'skills' => [16, 29, 31],
                'traits' => [23],
                'special' => 'Putrid Regurgitation',
                'description' => 'Once per game, Bilerot may use the Projectile Vomit Special Action. This may still be used even if Bilerot has already performed a Block action this turn.',
                'display' => true,
                'regions' => [],
                'rules' => [4],
            ],
            [
                'name' => 'The Black Gobbo',
                'ma' => '6',
                'st' => '2',
                'ag' => '3',
                'pa' => '3',
                'av' => '9',
                'cost' => 225000,
                'skills' => [5, 9, 10, 29],
                'traits' => [14, 22, 34, 35],
                'special' => 'Sneakiest of the Lot',
                'description' => 'If your team includes the Black Gobbo, you may commit two Foul actions per team turn, provided one of your Foul actions is committed by the Black Gobbo himself.',
                'display' => true,
                'regions' => [1, 7],
                'rules' => [],
            ],
            [
                'name' => 'Boa Kon\'ssstriktr',
                'ma' => '6',
                'st' => '3',
                'ag' => '3',
                'pa' => '4',
                'av' => '9',
                'cost' => 200000,
                'skills' => [5, 8, 9, 35],
                'traits' => [19, 23],
                'special' => 'Look into my Eyes',
                'description' => 'Once per game, if Boa starts his activation marking an opposition player with the ball, he may roll a D6. On a 1, nothing happens. On a 2+ the opposition player loses possession of the ball, Boa immediately gains possession of the ball and Boa’s activation immediately ends.',
                'display' => true,
                'regions' => [4],
                'rules' => [],
            ],
            [
                'name' => 'Bomber Dribblesnot',
                'ma' => '6',
                'st' => '2',
                'ag' => '3',
                'pa' => '3',
                'av' => '8',
                'cost' => 50000,
                'skills' => [5, 39],
                'traits' => [14, 23, 32, 33, 35],
                'special' => 'Kaboom!',
                'description' => 'Once per game, if an opposition player catches a Bomb thrown by Bomber, you can choose to have it explode immediately rather than rolling to see if the player can throw it again.',
                'display' => true,
                'regions' => [1, 7],
                'rules' => [],
            ],
            [
                'name' => 'Bryce ‘The Slice’ Cambuel',
                'ma' => '5',
                'st' => '3',
                'ag' => '4',
                'pa' => '0',
                'av' => '9',
                'cost' => 130000,
                'skills' => [62, 64],
                'traits' => [16, 23, 31, 33, ],
                'special' => 'Ghostly Flames',
                'description' => 'Once per half, when Bryce makes the Chainsaw Attack Special action as part of a Blitz action, he may add +4 to the Armour roll against an opponent rather +3.',
                'display' => true,
                'regions' => [6],
                'rules' => [],
            ],
            [
                'name' => '‘Captain’ Karina Von Riesz',
                'ma' => '7',
                'st' => '4',
                'ag' => '2',
                'pa' => '4',
                'av' => '9',
                'cost' => 230000,
                'skills' => [5, 6],
                'traits' => [12, 19, 23, 31],
                'special' => 'Tasty Morsel',
                'description' => 'Once per game, when Karina fails a Bloodlust roll, she may choose to bite an opposition player with a ST of 3 or lower as if they were a Thrall Lineman team-mate. Karina may note bite Star Players with this special rule.',
                'display' => true,
                'regions' => [6],
                'rules' => [],
            ],
            [
                'name' => 'Count Luthor von Drakenborg',
                'ma' => '6',
                'st' => '5',
                'ag' => '2',
                'pa' => '3',
                'av' => '10',
                'cost' => 340000,
                'skills' => [9, 13],
                'traits' => [19, 23, 31],
                'special' => 'Star of the Show',
                'description' => 'Once per game, when Count Luthor scores a touchdown, his controlling coach may gain one team re-roll. If this re-roll has not been used by the end of the next drive, it is lost.',
                'display' => true,
                'regions' => [6],
                'rules' => [],
            ],
            [
                'name' => 'Cindy Piewhistle',
                'ma' => '5',
                'st' => '2',
                'ag' => '3',
                'pa' => '3',
                'av' => '7',
                'cost' => 50000,
                'skills' => [5, 39, ],
                'traits' => [14, 23, 33, 35],
                'special' => 'All You Can Eat',
                'description' => 'Once per game, Cindy may perform two Throw Bomb Special actions rather than one, though she must commit to doing so before making the first action. If she does, immediately after performing the second Throw Bomb Special action roll a D6. On a 1-3 Cindy is immediately Sent Off.',
                'display' => true,
                'regions' => [3, 5],
                'rules' => [],
            ],
            [
                'name' => 'Deeproot Strongbranch',
                'ma' => '2',
                'st' => '7',
                'ag' => '5',
                'pa' => '4',
                'av' => '11',
                'cost' => 280000,
                'skills' => [13, 59, 62, 63, 64],
                'traits' => [23, 40, 41],
                'special' => 'Reliable',
                'description' => 'If Deeproot fumbles a Throw Team-mate action, the player that was to be thrown will bounce as normal but will automatically land safely.',
                'display' => true,
                'regions' => [3, 5],
                'rules' => [],
            ],
            [
                'name' => 'Dribl & Drull',
                'ma' => null,
                'st' => null,
                'ag' => null,
                'pa' => null,
                'av' => null,
                'cost' => 190000,
                'skills' => [],
                'traits' => [],
                'special' => 'A Sneaky Pair',
                'description' => 'Dribl & Drull must be hired as a pair and count as two Star Players. Additionally, whenever Dribl or Drull perform either a Stab or Foul action against an opposition player marked by both Dribl & Drull, they may apply a +1 modifier to the injury roll.',
                'display' => true,
                'pair_key' => 'd&d',
                'regions' => [4],
                'rules' => [],
            ],
            [
                'name' => 'Dribl',
                'ma' => '8',
                'st' => '2',
                'ag' => '3',
                'pa' => '4',
                'av' => '8',
                'cost' => null,
                'skills' => [5, 9, 10, 16],
                'traits' => [23, 35],
                'special' => 'A Sneaky Pair',
                'description' => 'Dribl & Drull must be hired as a pair and count as two Star Players. Additionally, whenever Dribl or Drull perform either a Stab or Foul action against an opposition player marked by both Dribl & Drull, they may apply a +1 modifier to the injury roll.',
                'display' => false,
                'pair_key' => 'd&d',
                'regions' => [],
                'rules' => [],
            ],
            [
                'name' => 'Drull',
                'ma' => '8',
                'st' => '2',
                'ag' => '3',
                'pa' => '4',
                'av' => '8',
                'cost' => null,
                'skills' => [5, 9],
                'traits' => [23, 34, 35],
                'special' => 'A Sneaky Pair',
                'description' => 'Dribl & Drull must be hired as a pair and count as two Star Players. Additionally, whenever Dribl or Drull perform either a Stab or Foul action against an opposition player marked by both Dribl & Drull, they may apply a +1 modifier to the injury roll.',
                'display' => false,
                'pair_key' => 'd&d',
                'regions' => [],
                'rules' => [],
            ],
            [
                'name' => 'Eldril Sidewinder',
                'ma' => '8',
                'st' => '3',
                'ag' => '2',
                'pa' => '5',
                'av' => '8',
                'cost' => 230000,
                'skills' => [1, 5, 46, 47],
                'traits' => [19, 23],
                'special' => 'Mesmerizing Gaze',
                'description' => 'Once per game, Eldril may re-roll a failed Agility test when attempting to use the Hypnotic Gaze trait.',
                'display' => true,
                'regions' => [2],
                'rules' => [],
            ],
            [
                'name' => 'Estelle La Veneaux',
                'ma' => '6',
                'st' => '3',
                'ag' => '3',
                'pa' => '4',
                'av' => '8',
                'cost' => 190000,
                'skills' => [5, 9, 29, 55],
                'traits' => [23],
                'special' => 'Baleful Hex',
                'description' => 'One per game, at the beginning of Estelle’s activation, choose an opposition player within five squares and roll a D6. On a 2+ the chosen player loses their Tackle Zone and cannot be activated until the end of the opposition’s next team turn.',
                'display' => true,
                'regions' => [4],
                'rules' => [],
            ],
            [
                'name' => 'Frank ‘n’ Stein',
                'ma' => '4',
                'st' => '5',
                'ag' => '4',
                'pa' => '0',
                'av' => '10',
                'cost' => 250000,
                'skills' => [53, 58, 62, 64],
                'traits' => [23, 31],
                'special' => 'Brutal Block',
                'description' => 'Once per game, when Frank ‘n’ Stein makes an Injury roll against an opponents a result of a Block action, he may choose to add an additional +1 modifier to the Injury roll. This modifier may be applied after the roll has been made.',
                'display' => true,
                'regions' => [5, 6],
                'rules' => [],
            ],
            [
                'name' => 'Fungus the Loon',
                'ma' => '4',
                'st' => '7',
                'ag' => '3',
                'pa' => '0',
                'av' => '8',
                'cost' => 80000,
                'skills' => [58],
                'traits' => [10, 23, 26, 33, 35],
                'special' => 'Whirling Dervish',
                'description' => 'Once per activation, Fungus may re-roll the D6 when determining which direction he moves in.',
                'display' => true,
                'regions' => [1, 7],
                'rules' => [],
            ],
            [
                'name' => 'Glart Smashrip',
                'ma' => '5',
                'st' => '4',
                'ag' => '4',
                'pa' => '0',
                'av' => '9',
                'cost' => 195000,
                'skills' => [13, 28, 54, 56, 62],
                'traits' => [23],
                'special' => 'Frenzied Rush',
                'description' => 'Once per game, when Glart performs a Blitz action, he may gain the Frenzy skill. You must declare this special rule is being used when Glart is activated. Glart may not use the Grab skill during a turn in which he uses this special rule.',
                'display' => true,
                'regions' => [7],
                'rules' => [2, 3, 4, 5, 6, 10],
            ],
            [
                'name' => 'Gloriel Summerbloom',
                'ma' => '7',
                'st' => '2',
                'ag' => '2',
                'pa' => '2',
                'av' => '8',
                'cost' => 150000,
                'skills' => [5, 9, 24, 39, 48],
                'traits' => [22],
                'special' => 'Shot to Nothing',
                'description' => 'Once per game, when Gloriel performs a Pass action, she may gain the Hail Mary Pass skill. You must declare this special rules is being used when Gloriel is activated.',
                'display' => true,
                'regions' => [2],
                'rules' => [],
            ],
            [
                'name' => 'Glotl Stop',
                'ma' => '6',
                'st' => '6',
                'ag' => '5',
                'pa' => '0',
                'av' => '10',
                'cost' => 270000,
                'skills' => [19, 35, 58, 62, 64],
                'traits' => [1, 23],
                'special' => 'Primal Savagery',
                'description' => 'Once per game, when Glotl fails an Animal Savagery roll, it may lash out at an opposition player rather than a team mate.',
                'display' => true,
                'regions' => [4],
                'rules' => [],
            ],
            [
                'name' => 'Grak & Crumbleberry',
                'ma' => null,
                'st' => null,
                'ag' => null,
                'pa' => null,
                'av' => null,
                'cost' => 250000,
                'skills' => [],
                'traits' => [],
                'special' => 'Two for One',
                'description' => 'Grak and Crumbleberry must be hired as a pair and count as two Star Players. However if either Grak or Crumbleberry is removed from play due to suffering a KO’ed or Casualty! result on the injury table, the other replaces the Loner (4+) trait with the Loner (2+) trait.',
                'display' => true,
                'pair_key' => 'g&c',
                'regions' => [],
                'rules' => [],
            ],
            [
                'name' => 'Grak',
                'ma' => '5',
                'st' => '5',
                'ag' => '4',
                'pa' => '4',
                'av' => '10',
                'cost' => null,
                'skills' => [58, 64],
                'traits' => [15, 20, 23],
                'special' => 'Two for One',
                'description' => 'Grak and Crumbleberry must be hired as a pair and count as two Star Players. However if either Grak or Crumbleberry is removed from play due to suffering a KO’ed or Casualty! result on the injury table, the other replaces the Loner (4+) trait with the Loner (2+) trait.',
                'display' => false,
                'pair_key' => 'g&c',
                'regions' => [],
                'rules' => [],
            ],
            [
                'name' => 'Crumbleberry',
                'ma' => '5',
                'st' => '2',
                'ag' => '3',
                'pa' => '6',
                'av' => '7',
                'cost' => null,
                'skills' => [5, 24],
                'traits' => [23, 32, 35],
                'special' => 'Two for One',
                'description' => 'Grak and Crumbleberry must be hired as a pair and count as two Star Players. However if either Grak or Crumbleberry is removed from play due to suffering a KO’ed or Casualty! result on the injury table, the other replaces the Loner (4+) trait with the Loner (2+) trait.',
                'display' => false,
                'pair_key' => 'g&c',
                'regions' => [],
                'rules' => [],
            ],
            [
                'name' => 'Grashnak Blackhoof',
                'ma' => '6',
                'st' => '6',
                'ag' => '4',
                'pa' => '0',
                'av' => '9',
                'cost' => 240000,
                'skills' => [19, 32, 58, 64],
                'traits' => [23, 43],
                'special' => 'Gored by the Bull',
                'description' => 'Once per game, when Grashnak performs a Blitz action, Grashnak may roll one additional Block dice against the opposition player, regardless of the opposition player’s Strength, to a maximum of three Block dice. If Grashnak performs a second Block action due to the Frenzy skill, this second Block action will also benefit from this rule.',
                'display' => true,
                'regions' => [],
                'rules' => [2, 3, 4, 5, 6, 10],
            ],
            [
                'name' => 'Gretchen Wachter ‘The Blood Bowl Widow’',
                'ma' => '7',
                'st' => '3',
                'ag' => '2',
                'pa' => '0',
                'av' => '9',
                'cost' => 260000,
                'skills' => [5, 6, 9, 22, 29, 31],
                'traits' => [23, 26, 31],
                'special' => 'Incorporeal',
                'description' => 'Once per game, after making an Agility test to dodge, Gretchen may choose to modify the dice roll by adding her Strength characteristic to it.',
                'display' => true,
                'regions' => [6],
                'rules' => [],
            ],
            [
                'name' => 'Griff Oberwald',
                'ma' => '7',
                'st' => '4',
                'ag' => '2',
                'pa' => '3',
                'av' => '9',
                'cost' => 280000,
                'skills' => [5, 11, 12, 13, 18],
                'traits' => [22],
                'special' => 'Consummate Professional',
                'description' => 'Once per game, Griff may re-roll one dice that was rolled either as a single roll, as part of a multiple dice roll or as part of a dice pool (this cannot be a dice that was rolled as part of an Armour, Injury or Casualty roll).',
                'display' => true,
                'regions' => [3, 5],
                'rules' => [],
            ],
            [
                'name' => 'Grim Ironjaw',
                'ma' => '5',
                'st' => '4',
                'ag' => '3',
                'pa' => '0',
                'av' => '9',
                'cost' => 200000,
                'skills' => [13, 14, 19, 60, 64],
                'traits' => [23],
                'special' => 'Slayer',
                'description' => 'Once per game, when an opposition player with a Strength characteristic of 5 or more is Knocked Down as the result of a Block action performed by Grim, you may apply an additional +1 modifier to either the Armour or Injury roll. This modifier may be applied after the roll has been made.',
                'display' => true,
                'regions' => [3, 5, 8],
                'rules' => [],
            ],
            [
                'name' => 'Guffle Pusmaw',
                'ma' => '5',
                'st' => '4',
                'ag' => '4',
                'pa' => '6',
                'av' => '10',
                'cost' => 180000,
                'skills' => [31, 34, 46, 47, ],
                'traits' => [23, 27],
                'special' => 'Quick Bite',
                'description' => 'Once per game, if Guffle is marking an opposing player who catches the ball, he may immediately make an unmodified Armour roll, and subsequent Injury roll if necessary, against that player. If the target\'s Armour is broken, Guffle immediately gains possession of the ball. No Turnover is caused as a result of using this special rule.',
                'display' => true,
                'regions' => [],
                'rules' => [4],
            ],
            [
                'name' => 'H’Thark the Unstoppable',
                'ma' => '6',
                'st' => '6',
                'ag' => '4',
                'pa' => '6',
                'av' => '10',
                'cost' => 300000,
                'skills' => [2, 11, 12, 13, 53, 56, 64],
                'traits' => [23],
                'special' => 'Unstoppable Momentum',
                'description' => 'Whenever H\'Thark performs a Blitz action, he may re-roll a single block dice.',
                'display' => true,
                'regions' => [1],
                'rules' => [10],
            ],
            [
                'name' => 'Hakflem Skuttlespike',
                'ma' => '9',
                'st' => '3',
                'ag' => '2',
                'pa' => '3',
                'av' => '8',
                'cost' => 210000,
                'skills' => [5, 30, 35, 37],
                'traits' => [23],
                'special' => 'Treacherous',
                'description' => 'Once per game, if a team-mate in an adjacent square to Hakflem is in possession of the ball when Hakflem is activated, that player may immediately be Knocked Down and Hakflem may take possession of the ball. No turnover is caused as a result of using this special rule.',
                'display' => true,
                'regions' => [7],
                'rules' => [2, 3, 4, 5, 6, 10],
            ],
            [
                'name' => 'Helmut Wolf',
                'ma' => '6',
                'st' => '3',
                'ag' => '3',
                'pa' => '0',
                'av' => '9',
                'cost' => 140000,
                'skills' => [21, 62],
                'traits' => [16, 23, 33],
                'special' => 'Old Pro',
                'description' => 'One per game, Helmut may use his Pro skill to re-roll a single dice rolled as part of an Armour roll.',
                'display' => true,
                'regions' => [],
                'rules' => [],
            ],
            [
                'name' => 'Ivan ‘the Animal’ Deathshroud',
                'ma' => '6',
                'st' => '4',
                'ag' => '4',
                'pa' => '5',
                'av' => '9',
                'cost' => 190000,
                'skills' => [13, 23, 25, 29, 56],
                'traits' => [23, 31],
                'special' => 'Dwarven Scourge',
                'description' => 'Once per game, when an opposition player is Knocked Down as a result of a Block action performed by Ivan, you may apply an additional +1 modifier to the Armour roll or Injury roll. If this is against a Dwarfen player from any team, this may instead be a +2 modifier.',
                'display' => true,
                'regions' => [6],
                'rules' => [],
            ],
            [
                'name' => 'Ivar Eriksson',
                'ma' => '6',
                'st' => '4',
                'ag' => '3',
                'pa' => '4',
                'av' => '9',
                'cost' => 245000,
                'skills' => [13, 25, 55],
                'traits' => [22],
                'special' => 'Raiding Party',
                'description' => 'Once per drive, whenever Ivar begins his activation, he may choose one Open player on his team within five squares. The chosen player may immediately move one square, ignoring Tackle Zones, though they must end this move Marking an opposition player.',
                'display' => true,
                'regions' => [5],
                'rules' => [],
            ],
            [
                'name' => 'Jeremiah Kool',
                'ma' => '8',
                'st' => '3',
                'ag' => '1',
                'pa' => '2',
                'av' => '9',
                'cost' => 320000,
                'skills' => [3, 5, 9, 13, 42, 46, 47, 48],
                'traits' => [23],
                'special' => 'The Flashing Blade',
                'description' => 'Once per game, at the start of his activation, Jeremiah may declare a Stab Special Action against an opposition player he is marking. After performing the Stab Special action, Jeremiah may then perform a Move Action before his turn ends.',
                'display' => true,
                'regions' => [2],
                'rules' => [],
            ],
            [
                'name' => 'Jordell Freshbreeze',
                'ma' => '8',
                'st' => '3',
                'ag' => '1',
                'pa' => '3',
                'av' => '8',
                'cost' => 250000,
                'skills' => [3, 5, 7, 9, 13],
                'traits' => [23],
                'special' => 'Swift as the Breeze',
                'description' => 'Once per game, Jordell can choose to pass a single Dodge, Leap or Rush test on a 2+, regardless on any modifiers.',
                'display' => true,
                'regions' => [2],
                'rules' => [],
            ],
            [
                'name' => 'Karla Von Kill',
                'ma' => '6',
                'st' => '4',
                'ag' => '3',
                'pa' => '4',
                'av' => '9',
                'cost' => 210000,
                'skills' => [5, 6, 13, 14],
                'traits' => [23],
                'special' => 'Indomitable',
                'description' => 'Once per game, when Karla successfully rolls to use her Dauntless skill, she may increase her Strength characteristic to double that of the nominated target of her Block action.',
                'display' => true,
                'regions' => [3, 4, 5],
                'rules' => [],
            ],
            [
                'name' => 'Kiroth Krakeneye',
                'ma' => '7',
                'st' => '3',
                'ag' => '2',
                'pa' => '3',
                'av' => '9',
                'cost' => 160000,
                'skills' => [25, 29, 31, 36, 47],
                'traits' => [23],
                'special' => 'Black Ink',
                'description' => 'Once per game, at the star of any of his activations, Kiroth can choose an opposition player he is marking. The chosen player loses their Tackle Zone until they are next activated.',
                'display' => true,
                'regions' => [2],
                'rules' => [],
            ],
            [
                'name' => 'Kreek Rustgouger',
                'ma' => '5',
                'st' => '7',
                'ag' => '4',
                'pa' => '0',
                'av' => '10',
                'cost' => 170000,
                'skills' => [35, 58],
                'traits' => [10, 23, 26, 33],
                'special' => 'I’ll Be Back!',
                'description' => 'The first time in a game that Kreek Rustgouger would be Sent-off as per the Secret Weapon trait, he is not Sent-off and instead may continue as part of the game.',
                'display' => true,
                'regions' => [7],
                'rules' => [2, 3, 4, 5, 6, 10],
            ],
            [
                'name' => 'Lord Borak the Despoiler',
                'ma' => '5',
                'st' => '5',
                'ag' => '3',
                'pa' => '5',
                'av' => '10',
                'cost' => 260000,
                'skills' => [10, 13, 17, 58],
                'traits' => [23],
                'special' => 'Lord of Chaos',
                'description' => 'A team that includes Lord Borak gains an extra Team re-roll for the first half of the game. If this Team re-roll is not used during the first half, it may be carried over into the second half. However, if Lord Borak is removed from play before this re-roll is used, it is lost.',
                'display' => true,
                'regions' => [],
                'rules' => [2, 3, 4, 5, 6, 10],
            ],
            [
                'name' => 'Maple Highgrove',
                'ma' => '3',
                'st' => '5',
                'ag' => '5',
                'pa' => '5',
                'av' => '11',
                'cost' => 210000,
                'skills' => [36, 52, 54, 58, 62, 64],
                'traits' => [23],
                'special' => 'Vicious Vines',
                'description' => 'Once per half, when Maple declares a Block action, he may do so against an opposition player who is 2 squares away, following all the normal rules for making a Block, though he may not follow up. This Block action cannot be part of a Blitz action.',
                'display' => true,
                'regions' => [3, 4, 5],
                'rules' => [],
            ],
            [
                'name' => 'Max Spleenripper',
                'ma' => '5',
                'st' => '4',
                'ag' => '4',
                'pa' => '0',
                'av' => '9',
                'cost' => 130000,
                'skills' => [],
                'traits' => [16, 23, 33],
                'special' => 'Maximum Carnage',
                'description' => 'Once per game, after Max performs a Chainsaw Attack Special action he may immediately perform another Chainsaw Attack Special action that targets a different player.',
                'display' => true,
                'regions' => [],
                'rules' => [3],
            ],
            [
                'name' => 'Mighty Zug',
                'ma' => '4',
                'st' => '5',
                'ag' => '4',
                'pa' => '6',
                'av' => '10',
                'cost' => 220000,
                'skills' => [13, 58],
                'traits' => [23],
                'special' => 'Crushing Blow',
                'description' => 'Once per game, when an opposition player is Knocked Down as the result of a Block action performed by Zug, you may apply an additional +1 modifier to the Armour roll. This modifier may be applied after the roll has been made.',
                'display' => true,
                'regions' => [3, 4, 5],
                'rules' => [],
            ],
            [
                'name' => 'Morg ‘n’ Thorg',
                'ma' => '6',
                'st' => '6',
                'ag' => '3',
                'pa' => '4',
                'av' => '11',
                'cost' => 380000,
                'skills' => [13, 59, 64],
                'traits' => [23, 40],
                'special' => 'The Ballista',
                'description' => 'Once per game, if Morg fails the Passing Ability test when making a Pass action or a Throw Team-mate action, you may re-roll the D6.',
                'display' => true,
                'regions' => [1, 2, 3, 4, 5, 7, 8],
                'rules' => [1, 2, 3, 4, 5, 7, 10],
            ],
            [
                'name' => 'Nobbla Blackwart',
                'ma' => '6',
                'st' => '2',
                'ag' => '3',
                'pa' => '0',
                'av' => '8',
                'cost' => 120000,
                'skills' => [5, 13],
                'traits' => [16, 23, 33, 35],
                'special' => 'Kick ’em While They’re Down!',
                'description' => 'Once per game, Nobbla may use the Chainsaw Attack Special action against a Prone or Stunned opposition player. This does not count as a Foul action and so Nobbla cannot be Sent-off when using this ability.',
                'display' => true,
                'regions' => [1, 7],
                'rules' => [],
            ],
            [
                'name' => 'Puggy Baconbreath',
                'ma' => '5',
                'st' => '3',
                'ag' => '3',
                'pa' => '4',
                'av' => '7',
                'cost' => 120000,
                'skills' => [5, 13, 46],
                'traits' => [22, 32, 35],
                'special' => 'Halfling Luck',
                'description' => 'Once per game, Puggy may re-roll one dice that was rolled either as a single dice, or as part of a dice pool (this cannot be a dice that was rolled part of an Armour, Injury, or Casualty roll).',
                'display' => true,
                'regions' => [3, 5],
                'rules' => [],
            ],
            [
                'name' => 'Rashnak Backstabber',
                'ma' => '7',
                'st' => '3',
                'ag' => '3',
                'pa' => '5',
                'av' => '8',
                'cost' => 130000,
                'skills' => [9, 10, 22],
                'traits' => [23, 34],
                'special' => 'Toxin Connoisseur',
                'description' => 'Once per game, when Rashnak successfully breaks an opposition player\'s armour as a result of a Stab Special action, you may apply an additional +1 modifier to the Injury roll. This modifier may be applied after the roll has been made.',
                'display' => true,
                'regions' => [1],
                'rules' => [],
            ],
            [
                'name' => 'Ripper Bolgrot',
                'ma' => '4',
                'st' => '6',
                'ag' => '5',
                'pa' => '4',
                'av' => '10',
                'cost' => 250000,
                'skills' => [54, 58],
                'traits' => [23, 31, 40],
                'special' => 'Thinking Man’s Troll',
                'description' => 'Once per half, Ripper may re-roll one dice that was rolled either as a single dice, as part of a multiple dice pool (this cannot be a dice that was rolled as part of an Armour, Injury or Casualty roll).',
                'display' => true,
                'regions' => [1, 7],
                'rules' => [],
            ],
            [
                'name' => 'Rodney Roachbait',
                'ma' => '6',
                'st' => '2',
                'ag' => '3',
                'pa' => '4',
                'av' => '7',
                'cost' => 70000,
                'skills' => [1, 3, 6, 9, 26, 47],
                'traits' => [23, 35],
                'special' => 'Catch of the Day',
                'description' => 'Once per half, if Rodney is Standing and begins his activation within 3 squares of a ball which is on the ground he may roll a D6. On a 1-2, nothing happens. On a 3+, Rodney immediately gains possession of the ball.',
                'display' => true,
                'regions' => [3],
                'rules' => [],
            ],
            [
                'name' => 'Rowana Forestfoot',
                'ma' => '6',
                'st' => '3',
                'ag' => '3',
                'pa' => '4',
                'av' => '8',
                'cost' => 160000,
                'skills' => [5, 6, 7, 32, 42, 54],
                'traits' => [23],
                'special' => 'Bounding Leap',
                'description' => 'Once per game, after declaring that she will Leap but before rolling any dice. Rowana may choose to use this special rule. If she does, Rowana suffers no negative modifiers for the Agility test to Leap and may choose to re-roll the result.',
                'display' => true,
                'regions' => [3],
                'rules' => [],
            ],
            [
                'name' => 'Roxanna Darknail',
                'ma' => '8',
                'st' => '3',
                'ag' => '1',
                'pa' => '4',
                'av' => '8',
                'cost' => 270000,
                'skills' => [5, 6, 7, 19, 56],
                'traits' => [23],
                'special' => 'Burst of Speed',
                'description' => 'Once per game, Roxanna may attempt to Rush three times, rather than the usual two. You may declare you are using this special rule after Roxanna has Rushed twice.',
                'display' => true,
                'regions' => [2],
                'rules' => [],
            ],
            [
                'name' => 'Rumbelow Sheepskin',
                'ma' => '6',
                'st' => '3',
                'ag' => '3',
                'pa' => '0',
                'av' => '8',
                'cost' => 170000,
                'skills' => [13, 25, 32, 56, 64],
                'traits' => [23, 26],
                'special' => 'Ram',
                'description' => 'Once per game, when an opposition player is Knocked Down as the result of a Block action performed by Rumbelow, you may apply an additional +1 modifier to either the Armour or Injury roll. This modifier may be applied after the roll has been made.',
                'display' => true,
                'regions' => [3, 5, 8],
                'rules' => [],
            ],
            [
                'name' => 'Scrappa Sorehead',
                'ma' => '7',
                'st' => '2',
                'ag' => '3',
                'pa' => '5',
                'av' => '8',
                'cost' => 130000,
                'skills' => [5, 11, 12, 16],
                'traits' => [23, 28, 32, 35],
                'special' => 'Yoink!',
                'description' => 'Once per game, when Scrappa attempts to interfere with a Pass action, he may roll a D6. On a 2+, Scrappa does not need to roll to interfere with the Pass action, instead he automatically makes an Interception and gains control of the ball.',
                'display' => true,
                'regions' => [1, 7],
                'rules' => [],
            ],
            [
                'name' => 'Scyla Anfingrimm',
                'ma' => '5',
                'st' => '5',
                'ag' => '4',
                'pa' => '0',
                'av' => '10',
                'cost' => 200000,
                'skills' => [19, 28, 35, 58, 64],
                'traits' => [23, 43],
                'special' => 'Fury of the Blood God',
                'description' => 'Once per game, if Scyla rolls a 1 for his Unchannelled Fury roll after declaring a Block action, instead of applying the usual effects of Unchannelled Fury, Scyla may perform two Block actions instead.',
                'display' => true,
                'regions' => [],
                'rules' => [],
            ],
            [
                'name' => 'Skitter Stab-Stab',
                'ma' => '9',
                'st' => '2',
                'ag' => '2',
                'pa' => '4',
                'av' => '8',
                'cost' => 150000,
                'skills' => [5, 22, 35],
                'traits' => [23, 34],
                'special' => 'Master Assassin',
                'description' => 'Once per game, when Skitter successfully breaks an opposition player\'s armour as a result of a Stab Special action, he may choose to re-roll the Injury roll.',
                'display' => true,
                'regions' => [7],
                'rules' => [2, 3, 4, 5, 6, 10],
            ],
            [
                'name' => 'Skrorg Snowpelt',
                'ma' => '5',
                'st' => '5',
                'ag' => '4',
                'pa' => '0',
                'av' => '9',
                'cost' => 250000,
                'skills' => [28, 29, 56, 58],
                'traits' => [23],
                'special' => 'Pump Up the Crowd',
                'description' => 'Once per game, when Skrorg causes an opposition player to be removed as a Casualty as the result of a Block action, Skrorg’s controlling coach gains one team re-roll. If this re-roll has not been used by the end of the drive, it is lost.',
                'display' => true,
                'regions' => [5],
                'rules' => [],
            ],
            [
                'name' => 'Skrull Halfheight',
                'ma' => '6',
                'st' => '3',
                'ag' => '4',
                'pa' => '4',
                'av' => '9',
                'cost' => 150000,
                'skills' => [24, 39, 46, 48, 64],
                'traits' => [23, 31],
                'special' => 'Strong Passing Game',
                'description' => 'Once per game, after making a Passing Ability test to perform a Pass action, Skrull may choose to modify the dice roll by adding his Strength characteristic to it.',
                'display' => true,
                'regions' => [6, 8],
                'rules' => [],
            ],
            [
                'name' => 'The Swift Twins',
                'ma' => null,
                'st' => null,
                'ag' => null,
                'pa' => null,
                'av' => null,
                'cost' => 340000,
                'skills' => [],
                'traits' => [],
                'special' => 'Two for One',
                'description' => 'The Swift Twins must be hired as a pair and count as two Star Players. However if either Lucien or Valen is removed from play due to suffering a KO’ed or Casualty! result on the injury table, the other replaces the Loner (4+) trait with the Loner (2+) trait.',
                'display' => true,
                'pair_key' => 'swift',
                'regions' => [2],
                'rules' => [],
            ],
            [
                'name' => 'Lucien Swift',
                'ma' => '7',
                'st' => '3',
                'ag' => '2',
                'pa' => '5',
                'av' => '9',
                'cost' => null,
                'skills' => [13, 25, 58],
                'traits' => [23],
                'special' => 'Two for One',
                'description' => 'The Swift Twins must be hired as a pair and count as two Star Players. However if either Lucien or Valen is removed from play due to suffering a KO’ed or Casualty! result on the injury table, the other replaces the Loner (4+) trait with the Loner (2+) trait.',
                'display' => false,
                'pair_key' => 'swift',
                'regions' => [],
                'rules' => [],
            ],
            [
                'name' => 'Valen Swift',
                'ma' => '7',
                'st' => '3',
                'ag' => '2',
                'pa' => '2',
                'av' => '8',
                'cost' => null,
                'skills' => [24, 39, 46, 48, 50],
                'traits' => [23],
                'special' => 'Two for One',
                'description' => 'The Swift Twins must be hired as a pair and count as two Star Players. However if either Lucien or Valen is removed from play due to suffering a KO’ed or Casualty! result on the injury table, the other replaces the Loner (4+) trait with the Loner (2+) trait.',
                'display' => false,
                'pair_key' => 'swift',
                'regions' => [],
                'rules' => [],
            ],
            [
                'name' => 'Swiftvine Glimmershard',
                'ma' => '7',
                'st' => '2',
                'ag' => '3',
                'pa' => '5',
                'av' => '7',
                'cost' => 110000,
                'skills' => [9, 18, 29],
                'traits' => [23, 34, 35],
                'special' => 'Furious Outburst',
                'description' => 'Once per half, so long as she is standing at the start of her activation, Swiftvine can place herself adjacent to a standing opposition player within 3 squares of her and immediately make a Stab Special action against them. She may then place herself in an unoccupied square within 3 squares of her new position. Her activation then immediately ends. This counts as the team\'s Blitz action for the turn.',
                'display' => true,
                'regions' => [2, 3],
                'rules' => [],
            ],
            [
                'name' => 'Thorsson Stoutmead',
                'ma' => '6',
                'st' => '3',
                'ag' => '4',
                'pa' => '3',
                'av' => '8',
                'cost' => 170000,
                'skills' => [13, 64],
                'traits' => [23, 44],
                'special' => 'Beer Barrel Bash!',
                'description' => 'Once per drive, at the start of his activation, Thorsson may perform a Throw Keg Special action. When he does, select an opposition player within three squares of Thorsson and roll a D6. On a 3+, the player is immediately Knocked Down. However, on a 1, Thorsson is Knocked Down instead.',
                'display' => true,
                'regions' => [5],
                'rules' => [],
            ],
            [
                'name' => 'Varag Ghoul-Chewer',
                'ma' => '6',
                'st' => '5',
                'ag' => '3',
                'pa' => '5',
                'av' => '10',
                'cost' => 280000,
                'skills' => [6, 13, 58, 64],
                'traits' => [23],
                'special' => 'Crushing Blow',
                'description' => 'Once per game, when an opposition player is Knocked Down as the result of a Block action performed by Varag, you may apply an additional +1 modifier to the Armour roll. This modifier may be applied after the roll has been made.',
                'display' => true,
                'regions' => [1, 7],
                'rules' => [],
            ],
            [
                'name' => 'Grombrindal, the White Dwarf',
                'ma' => '5',
                'st' => '3',
                'ag' => '3',
                'pa' => '4',
                'av' => '10',
                'cost' => 210000,
                'skills' => [13, 14, 58, 62, 64],
                'traits' => [23],
                'special' => 'Wisdom of the White Dwarf',
                'description' => 'Once per team turn, when one of Grombrindal’s team-mates that is in an adjacent square is activated, that player gains either the Break Tackle, Dauntless, Mighty Blow (+1), or Sure Feet skill until the end of their activation.',
                'display' => true,
                'regions' => [3, 4, 5, 8],
                'rules' => [],
            ],
            [
                'name' => 'Wilhelm Chaney',
                'ma' => '8',
                'st' => '4',
                'ag' => '3',
                'pa' => '4',
                'av' => '9',
                'cost' => 220000,
                'skills' => [1, 19, 26, 28],
                'traits' => [23, 31],
                'special' => 'Savage Mauling',
                'description' => 'Once per game, when Wilhelm makes an Injury roll against an opposing player, he may choose to re-roll the result.',
                'display' => true,
                'regions' => [6],
                'rules' => [],
            ],
            [
                'name' => 'Willow Rosebark',
                'ma' => '5',
                'st' => '4',
                'ag' => '3',
                'pa' => '6',
                'av' => '9',
                'cost' => 150000,
                'skills' => [9, 14, 64],
                'traits' => [23],
                'special' => 'Indomitable',
                'description' => 'Once per game, when Willlow successfully rolls to use her Dauntless skill, she may increase her Strength characteristic to double that of the nominated target of her Block action.',
                'display' => true,
                'regions' => [2],
                'rules' => [],
            ],
            [
                'name' => 'Withergrasp Doubledrool',
                'ma' => '6',
                'st' => '3',
                'ag' => '4',
                'pa' => '4',
                'av' => '9',
                'cost' => 170000,
                'skills' => [25, 26, 35, 36, 37],
                'traits' => [23],
                'special' => 'Watch Out!',
                'description' => 'The first time each half that Withergrasp is the target of an opposition player’s Block action, he counts as having the Dodge skill.',
                'display' => true,
                'regions' => [],
                'rules' => [2, 3, 4, 5, 6, 10],
            ],
            [
                'name' => 'Zolcath the Zoat',
                'ma' => '5',
                'st' => '5',
                'ag' => '4',
                'pa' => '5',
                'av' => '10',
                'cost' => 230000,
                'skills' => [12, 29, 35, 56, 58],
                'traits' => [23, 31],
                'special' => 'Excuse Me, Are You a Zoat?',
                'description' => 'Once per game, when Zolcath is activated, he may gain the Hypnotic Gaze trait. You must declare this special rule is being used when Zolcath is activated.',
                'display' => true,
                'regions' => [2, 4],
                'rules' => [],
            ],
            [
                'name' => 'Zzharg Madeye',
                'ma' => '4',
                'st' => '4',
                'ag' => '4',
                'pa' => '3',
                'av' => '10',
                'cost' => 130000,
                'skills' => [24, 40, 44, 46, 64],
                'traits' => [23, 33],
                'special' => 'Then I Started Blastin\'!',
                'description' => 'Once per half, at the start of his activation, Zzharg may perform a Blunderbuss Blast Special action. When he does, select a Standing opposition player within 3 squares of Zzharg and roll a D6. On a 3+, the selected player is hit; immediately make an unmodified Armour roll, and subsequent Injury roll if necessary, against the selected player. On a 2, the opposing Coach selects a player (from either team, but not Zzharg) within 3 squares of the originally selected player to be hit instead. On a 1, Zzharg is hit instead. If the armour of the player hit is not broken, nothing happens.',
                'display' => true,
                'regions' => [1],
                'rules' => [10],
            ],
//            [
//                'name' => '',
//                'ma' => '6',
//                'st' => '3',
//                'ag' => '3',
//                'pa' => '0',
//                'av' => '9',
//                'cost' => null,
//                'skills' => [],
//                'traits' => [],
//                'special' => '',
//                'description' => '',
//                'display' => true,
//                'regions' => [],
//                'rules' => [],
//            ],
        ];

        $playersByPairKey = [];

        foreach ($starPlayers as $starPlayer) {
            $skills = $starPlayer['skills'];
            $traits = $starPlayer['traits'];
            $regions = $starPlayer['regions'] ?? [];
            $rules = $starPlayer['rules'] ?? [];
            $pairKey = $starPlayer['pair_key'] ?? null;
            unset($starPlayer['skills'], $starPlayer['traits'], $starPlayer['regions'], $starPlayer['rules']);

//            $player = \App\Models\StarPlayer::updateOrCreate($starPlayer);

            $player = \App\Models\StarPlayer::updateOrCreate(['name' => $starPlayer['name']], $starPlayer);

            if ($pairKey) {
                $playersByPairKey[$pairKey][] = $player;
            };

            foreach ($skills as $skill) {
                DB::table('star_player_skills')->insert([
                    'star_player_id' => $player->id,
                    'star_player_skill_id' => $skill,
                ]);
            }

            foreach ($traits as $trait) {
                DB::table('star_player_traits')->insert([
                    'star_player_id' => $player->id,
                    'star_player_trait_id' => $trait,
                ]);
            }

            foreach ($regions as $region) {
                DB::table('star_player_regions')->insert([
                    'star_player_id' => $player->id,
                    'star_player_region_id' => $region,
                ]);
            }

            foreach ($rules as $rule) {
                DB::table('star_player_team_rules')->insert([
                    'star_player_id' => $player->id,
                    'star_player_team_rule_id' => $rule,
                ]);
            }
        }
    }
}
